### ISSUE TITLE
PHP fatal error when updating tax rules in WooCommerce

### ISSUE THREAD

**Issue by marcinkrzeminski** [xwp/stream#1649]
# Bug Report

This bug was reported via contact form on our website.

## Expected Behavior

Describe what should happen.

## Actual Behavior

Describe what actually happens.

```php
[16-Dec-2024 16:45:35 UTC] PHP Fatal error: Uncaught ValueError: The arguments array must contain 4 items, 1 given in /home/mbzcooq/public_html/wp-content/plugins/stream/classes/class-log.php:127Stack trace:#0 /home/mbzcooq/public_html/wp-content/plugins/stream/classes/class-log.php(127): vsprintf()#1 [internal function]: WP_Stream\Log->log()#2 /home/mbzcooq/public_html/wp-content/plugins/stream/classes/class-connector.php(178): call_user_func_array()#3 /home/mbzcooq/public_html/wp-content/plugins/stream/connectors/class-connector-woocommerce.php(632): WP_Stream\Connector->log()#4 [internal function]: WP_Stream\Connector_Woocommerce->callback_woocommerce_tax_rate_updated()#5 /home/mbzcooq/public_html/wp-content/plugins/stream/classes/class-connector.php(127): call_user_func_array()#6 /home/mbzcooq/public_html/wp-includes/class-wp-hook.php(324): WP_Stream\Connector->callback()#7 /home/mbzcooq/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()#8 /home/mbzcooq/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()#9 /home/mbzcooq/public_html/wp-content/plugins/woocommerce/includes/class-wc-tax.php(1110): do_action()#10 /home/mbzcooq/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(2971): WC_Tax::_update_tax_rate()#11 /home/mbzcooq/public_html/wp-includes/class-wp-hook.php(324): WC_AJAX::tax_rates_save_changes()#12 /home/mbzcooq/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()#13 /home/mbzcooq/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()#14 /home/mbzcooq/public_html/wp-admin/admin-ajax.php(192): do_action()#15 {main}thrown in /home/mbzcooq/public_html/wp-content/plugins/stream/classes/class-log.php on line 127
```

## Steps to Reproduce the Problem

1. Go to Settings / Taxes (you need to have manual taxes setup enabled).
2. Add a tax rule if you don't have one. Click Save changes
3. Edit the tax value and click Save changes
4. The spinner will keep spinning, unless you refresh the site

## Screenshots

Drag and drop screenshots in this area that help illustrate the problem.

## System Information

- Stream plugin version:
- WordPress version:
- PHP version:
- Browser:
- Computer operating system:

**Comment by marcinkrzeminski** [comment]
Can't reproduce it on two different setups.
