### ISSUE TITLE
Custom wp-content location causes activation error

### ISSUE THREAD

**Issue by szepeviktor** [xwp/stream#731]
On OpenShift:
```
Fatal error: Uncaught exception 'Exception' with message 
'Plugin dir is not inside of WP_CONTENT_DIR' in /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/classes/class-plugin.php:214
 Stack trace: #0 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/classes/class-plugin.php(60): WP_Stream\Plugin->locate_plugin() 
#1 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/stream.php(37): WP_Stream\Plugin->__construct() 
#2 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/current/wp-admin/plugins.php(153): include('/var/lib/opensh...') 
#3 /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/current/wp-admin/plugins.php(155): plugin_sandbox_scrape('stream/stream.p...') 
#4 {main} thrown in /var/lib/openshift/53f86113e0b8cd116c0001cf/app-root/data/plugins/stream/classes/class-plugin.php on line 214 
```

**Comment by lukecarbis** [comment]
Thanks for the report @szepevikto.
